### ISSUE TITLE
混合翻译如何分离

### ISSUE THREAD

**Issue by OPPO9008** [Abcuders/TextForApiTranslation#1]
https://github.com/Abcuders/TextForApiTranslation/blob/cfb1d46a1338d4f82fd1ae3a1fca252edaec2b07/1.0.0/TextForApiTranslation.py#L18

翻译是要对键值对的

**Comment by Abcuders** [comment]
这里把翻译混合起来是因为小牛官网上写了可以用/n分隔开,以让小牛一次性翻译多条内容,后面又根据/n分离开,当然在混合部分就已经对原文内容中存在的/n做了替换,后面也会换回来的,希望我理解对了您的提问的意思,如果不对,能否请您给一个详细的例子
